version: "3.7"

services:
  pg-database:
    container_name: pg-database
    image: 'postgres:12'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=CRUD
    volumes:
      - pgdata1:/var/lib/postgresql/data

  app:
    build:
      dockerfile: Dockerfile
      context: "./backend"
#    env_file:
#      - backend/.env
    environment:
      - PORT=5000
      - DB_NAME=CRUD
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=pg-database
      - DB_PORT=5432
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - postgres-compose-network
    restart: on-failure
#    command: >
#      node app.js
    depends_on:
     - pg-database

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf


networks:
  postgres-compose-network:
    driver: bridge

volumes:
  pgdata1: { }
